[package]
name = "dlc-venc-adaptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256kfun = "0.7"
rand = "0.8"
anyhow = "1"
schnorr_fun = "0.7"
sigma_fun = "0.4"
sha2 = "0.9"
rand_chacha = "0.3"
